runtime: nodejs18
handlers:
  - url: /.*
    static_files: out/index.html
    upload: out/index.html
    secure: always
    expiration: "0s"
  - url: /(.*\..+)$
    static_files: out/\1
    upload: out/.*
    secure: always
  - url: /(.*)
    static_files: out/\1/index.html
    upload: out/.*/index.html
    secure: always
    expiration: "0s"
